version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: oridam_postgres
    restart: always
    environment:
      POSTGRES_USER: oridam_user
      POSTGRES_PASSWORD: oridam_password
      POSTGRES_DB: oridam_db
    ports:
      - "5432:5432"
    volumes:
      - oridam_pgdata:/var/lib/postgresql/data

volumes:
  oridam_pgdata:
